/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Candidate {
  'id' : bigint,
  'bio' : string,
  'yearsOfExperience' : bigint,
  'expectedSalary' : bigint,
  'owner' : Principal,
  'name' : string,
  'createdAt' : Time,
  'email' : string,
  'resumeFile' : [] | [ExternalBlob],
  'isProfileActive' : boolean,
  'specialization' : string,
  'phone' : string,
  'skills' : string,
  'qualification' : string,
  'location' : string,
  'currentSalary' : bigint,
}
export interface Employer {
  'id' : bigint,
  'contactName' : string,
  'about' : string,
  'owner' : Principal,
  'createdAt' : Time,
  'email' : string,
  'website' : string,
  'companyName' : string,
  'companySize' : string,
  'phone' : string,
  'location' : string,
  'industry' : string,
}
export type ExternalBlob = Uint8Array;
export interface JobPosting {
  'id' : bigint,
  'title' : string,
  'postedAt' : Time,
  'description' : string,
  'qualifications' : string,
  'isActive' : boolean,
  'maxExperience' : bigint,
  'minExperience' : bigint,
  'employerId' : bigint,
  'salaryMax' : bigint,
  'salaryMin' : bigint,
  'skills' : string,
  'specializations' : string,
  'location' : string,
}
export type Time = bigint;
export interface UserProfile { 'name' : string, 'role' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'applyToJob' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createJobPosting' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      bigint,
      bigint,
      string,
      bigint,
      bigint,
      string,
      string,
    ],
    bigint
  >,
  'getAllActiveJobPostings' : ActorMethod<[], Array<JobPosting>>,
  'getApplicationsForJob' : ActorMethod<[bigint], Array<Candidate>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCandidateById' : ActorMethod<[bigint], [] | [Candidate]>,
  'getEmployerById' : ActorMethod<[bigint], [] | [Employer]>,
  'getJobPostingById' : ActorMethod<[bigint], [] | [JobPosting]>,
  'getJobPostingsByEmployer' : ActorMethod<[bigint], Array<JobPosting>>,
  'getMyEmployerProfile' : ActorMethod<[], [] | [Employer]>,
  'getMyProfile' : ActorMethod<[], [] | [Candidate]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerCandidate' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      bigint,
      string,
      bigint,
      bigint,
      string,
      string,
    ],
    bigint
  >,
  'registerEmployer' : ActorMethod<
    [string, string, string, string, string, string, string, string, string],
    bigint
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchCandidates' : ActorMethod<
    [
      string,
      [] | [string],
      [] | [string],
      [] | [bigint],
      [] | [bigint],
      [] | [string],
    ],
    Array<Candidate>
  >,
  'toggleJobPostingActive' : ActorMethod<[bigint], boolean>,
  'toggleProfileActive' : ActorMethod<[bigint], boolean>,
  'updateCandidateProfile' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      string,
      string,
      bigint,
      string,
      bigint,
      bigint,
      string,
      string,
    ],
    undefined
  >,
  'updateEmployerProfile' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
    ],
    undefined
  >,
  'updateJobPosting' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      bigint,
      bigint,
      string,
      bigint,
      bigint,
      string,
      string,
    ],
    undefined
  >,
  'uploadResume' : ActorMethod<[bigint, ExternalBlob], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];