/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const JobPosting = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'postedAt' : Time,
  'description' : IDL.Text,
  'qualifications' : IDL.Text,
  'isActive' : IDL.Bool,
  'maxExperience' : IDL.Nat,
  'minExperience' : IDL.Nat,
  'employerId' : IDL.Nat,
  'salaryMax' : IDL.Nat,
  'salaryMin' : IDL.Nat,
  'skills' : IDL.Text,
  'specializations' : IDL.Text,
  'location' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Candidate = IDL.Record({
  'id' : IDL.Nat,
  'bio' : IDL.Text,
  'yearsOfExperience' : IDL.Nat,
  'expectedSalary' : IDL.Nat,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : Time,
  'email' : IDL.Text,
  'resumeFile' : IDL.Opt(ExternalBlob),
  'isProfileActive' : IDL.Bool,
  'specialization' : IDL.Text,
  'phone' : IDL.Text,
  'skills' : IDL.Text,
  'qualification' : IDL.Text,
  'location' : IDL.Text,
  'currentSalary' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
export const Employer = IDL.Record({
  'id' : IDL.Nat,
  'contactName' : IDL.Text,
  'about' : IDL.Text,
  'owner' : IDL.Principal,
  'createdAt' : Time,
  'email' : IDL.Text,
  'website' : IDL.Text,
  'companyName' : IDL.Text,
  'companySize' : IDL.Text,
  'phone' : IDL.Text,
  'location' : IDL.Text,
  'industry' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'applyToJob' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createJobPosting' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'getAllActiveJobPostings' : IDL.Func([], [IDL.Vec(JobPosting)], ['query']),
  'getApplicationsForJob' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(Candidate)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCandidateById' : IDL.Func([IDL.Nat], [IDL.Opt(Candidate)], ['query']),
  'getEmployerById' : IDL.Func([IDL.Nat], [IDL.Opt(Employer)], ['query']),
  'getJobPostingById' : IDL.Func([IDL.Nat], [IDL.Opt(JobPosting)], ['query']),
  'getJobPostingsByEmployer' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(JobPosting)],
      ['query'],
    ),
  'getMyEmployerProfile' : IDL.Func([], [IDL.Opt(Employer)], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(Candidate)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerCandidate' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'registerEmployer' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchCandidates' : IDL.Func(
      [
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Text),
      ],
      [IDL.Vec(Candidate)],
      ['query'],
    ),
  'toggleJobPostingActive' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'toggleProfileActive' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'updateCandidateProfile' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
  'updateEmployerProfile' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
  'updateJobPosting' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
  'uploadResume' : IDL.Func([IDL.Nat, ExternalBlob], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const JobPosting = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'postedAt' : Time,
    'description' : IDL.Text,
    'qualifications' : IDL.Text,
    'isActive' : IDL.Bool,
    'maxExperience' : IDL.Nat,
    'minExperience' : IDL.Nat,
    'employerId' : IDL.Nat,
    'salaryMax' : IDL.Nat,
    'salaryMin' : IDL.Nat,
    'skills' : IDL.Text,
    'specializations' : IDL.Text,
    'location' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Candidate = IDL.Record({
    'id' : IDL.Nat,
    'bio' : IDL.Text,
    'yearsOfExperience' : IDL.Nat,
    'expectedSalary' : IDL.Nat,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : Time,
    'email' : IDL.Text,
    'resumeFile' : IDL.Opt(ExternalBlob),
    'isProfileActive' : IDL.Bool,
    'specialization' : IDL.Text,
    'phone' : IDL.Text,
    'skills' : IDL.Text,
    'qualification' : IDL.Text,
    'location' : IDL.Text,
    'currentSalary' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
  const Employer = IDL.Record({
    'id' : IDL.Nat,
    'contactName' : IDL.Text,
    'about' : IDL.Text,
    'owner' : IDL.Principal,
    'createdAt' : Time,
    'email' : IDL.Text,
    'website' : IDL.Text,
    'companyName' : IDL.Text,
    'companySize' : IDL.Text,
    'phone' : IDL.Text,
    'location' : IDL.Text,
    'industry' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'applyToJob' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createJobPosting' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'getAllActiveJobPostings' : IDL.Func([], [IDL.Vec(JobPosting)], ['query']),
    'getApplicationsForJob' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Candidate)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCandidateById' : IDL.Func([IDL.Nat], [IDL.Opt(Candidate)], ['query']),
    'getEmployerById' : IDL.Func([IDL.Nat], [IDL.Opt(Employer)], ['query']),
    'getJobPostingById' : IDL.Func([IDL.Nat], [IDL.Opt(JobPosting)], ['query']),
    'getJobPostingsByEmployer' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(JobPosting)],
        ['query'],
      ),
    'getMyEmployerProfile' : IDL.Func([], [IDL.Opt(Employer)], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(Candidate)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerCandidate' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'registerEmployer' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchCandidates' : IDL.Func(
        [
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Text),
        ],
        [IDL.Vec(Candidate)],
        ['query'],
      ),
    'toggleJobPostingActive' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'toggleProfileActive' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'updateCandidateProfile' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'updateEmployerProfile' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'updateJobPosting' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'uploadResume' : IDL.Func([IDL.Nat, ExternalBlob], [], []),
  });
};

export const init = ({ IDL }) => { return []; };